spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agrarian-services
    username: db_admin
    password: db_admin
    driver-class-name: org.postgresql.Driver
    hikari:
      transaction-isolation: REPEATABLE_READ
      connection-timeout: 20000
      maximum-pool-size: 10
      max-lifetime: 1000
      auto-commit: off
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
  liquibase:
    change-log: classpath:liquibase/master.yml


logging:
  level:
    "liquibase": info